### ISSUE TITLE
Simplify. Indentation

### ISSUE THREAD

**Issue by kalverra** [millermaryc/prj-rev-bwfs-dasmoto#3]
https://github.com/millermaryc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L12-L40

Work on your indentation's consistency. https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/ and https://google.github.io/styleguide/htmlcssguide.html

**Comment by millermaryc** [comment]
I press return on my keyboard to start a new line when text is long. Should I continue to do this or is it confusing the spacing in the text editor?
