### ISSUE TITLE
Simplify. CSS organization

### ISSUE THREAD

**Issue by kalverra** [millermaryc/prj-rev-bwfs-dasmoto#5]
https://github.com/millermaryc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/CSS/index.css#L1-L33

Use spacing and indentation to help organize your CSS. https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines

Also look to condense CSS into as few tags and styles as possible. You use helvetica a lot, just put it into one tag.

**Comment by millermaryc** [comment]
I have read over the link you provided, some of it makes sense and some not so much. I hope as I continue on it will be come more clear. I printed out a copy of the link and will try to follow it as I continue to create new webpages. Is there a text editor that assists with proper structure? I am currently using Atom.
